name: firs-actions-test
on: [push]
jobs:
  jb1:
    runs-on: ubuntu-latest
    steps:
      - run: lsb_release -a > err.txt
      - run: cat err.txt
      - run: echo "test aciton echo here"

